# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
value: prisma_access_load_config_partial_api_v90
# label used for menu selection
label: Prisma Access Load Config Partial using API for Full Config v90
description: |
  Prisma Access load config partial skillet to merge configuration elements for imported file
  and creates a certificate and CA used in the mobile user template

type: panorama-gpcs

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Prisma Access

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
variables:

  - name: conf_filename
    description: name of imported file
    default: prisma_access_full_config.xml
    type_hint: text
    help_text: file name used in the load config partial commands
  - name: load_conf_options
    description: choose load config partial items
    default: ['service', 'mobile']
    type_hint: checkbox
    cbx_list:
      - key: Service Setup
        value: service
      - key: Mobile Users
        value: mobile

snippets:

  - name: svc_conn_template
    when: "'service' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Service_Conn_Template"]</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Service_Conn_Template"]</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: svc_conn_template_stack
    when: "'service' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain']/template-stack/entry[@name='Service_Conn_Template_Stack"]</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain']/template-stack/entry[@name='Service_Conn_Template_Stack"]</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: svc_conn_device_group
    when: "'service' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain']/device-group/entry[@name="Service_Conn_Device_Group"]</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain']/device-group/entry[@name="Service_Conn_Device_Group"]</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: svc_conn_onboarding
    when: "'service' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain']/plugins/cloud_services/service-connection</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain']/plugins/cloud_services/service-connection</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: mobile_user_template
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Mobile_User_Template"]</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Mobile_User_Template"]</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: set_template_target
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <set>
        <system>
          <setting>
            <target>
              <template>
                <name>Mobile_User_Template</name>
              </template>
            </target>
          </setting>
        </system>
      </set>

  - name: ca_cert_gen
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <request>
        <certificate>
          <generate>
            <ca>yes</ca>
            <certificate-name>Authentication Cookie CA</certificate-name>
            <name>Authentication Cookie CA</name>
            <algorithm>
              <RSA>
                <rsa-nbits>2048</rsa-nbits>
              </RSA>
            </algorithm>
          </generate>
        </certificate>
      </request>

  - name: ca_cert_gen
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <request>
        <certificate>
          <generate>
            <certificate-name>Authentication Cookie Cert</certificate-name>
            <name>Authentication Cookie Cert</name>
            <algorithm>
              <RSA>
                <rsa-nbits>2048</rsa-nbits>
              </RSA>
            </algorithm>
            <digest>sha256</digest>
            <ca>no</ca>
            <signed-by>Authentication Cookie CA</signed-by>
          </generate>
        </certificate>
      </request>

  - name: set_template_target_none
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <set>
        <system>
          <setting>
            <target>
              <none/>
            </target>
          </setting>
        </system>
      </set>

  - name: mobile_user_template_stack
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain']/template-stack/entry[@name='Mobile_User_Template_Stack"]</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain']/template-stack/entry[@name='Mobile_User_Template_Stack"]</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: mobile_user_device_group
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain']/device-group/entry[@name="Mobile_User_Device_Group"]</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain']/device-group/entry[@name="Mobile_User_Device_Group"]</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

  - name: mobile_user_onboarding
    when: "'mobile' in load_conf_options"
    cmd: op
    cmd_str: |-
      <load>
          <config>
              <partial>
                  <from-xpath>/config/devices/entry[@name="localhost.localdomain']/plugins/cloud_services/mobile-users</from-xpath>
                  <to-xpath>/config/devices/entry[@name="localhost.localdomain']/plugins/cloud_services/mobile-users</to-xpath>
                  <mode>merge</mode>
                  <from>{{ conf_filename }}</from>
              </partial>
          </config>
      </load>

# ---------------------------------------------------------------------
# end of snippets section